// Generated by Figma Extraction Script
// Source: https://www.figma.com/file/hLCQmALohG2t64j2mPLuNr

import React from 'react';

export interface ThemeColors {
  "White": string;
  "M3/sys/light/on-surface": string;
  "M3/sys/light/error": string;
  "TextIcon/OnNeutral": string;
  "Foundation /Blue/blue-3": string;
  "TextIcon/MidEmp": string;
  "Foundation /Black/black-4": string;
  "TextIcon/LowEmp": string;
  "Foundation /Black/black-7": string;
  "Foundation /Blue/blue-1": string;
  "M3/sys/light/on-tertiary": string;
  "Surface/NeutralBTN": string;
  "Foundation/gray/gray-4": string;
  "Foundation/gray/gray-8": string;
  "Foundation/gray/gray-6": string;
  "Foundation /Blue/blue-12": string;
  "Foundation /Black/black-1": string;
  "Foundation/black/text": string;
  "Foundation/black/bg": string;
  "Foundation/white/text": string;
  "Foundation/white/bg": string;
  "Foundation/gray/gray-5": string;
  "Foundation/gray/gray-7": string;
  "Foundation/gray/gray-2": string;
  "Foundation /Blue/blue-2": string;
  "Foundation /Blue/blue-4": string;
  "Foundation /Blue/blue-5": string;
  "Foundation /Blue/blue-6": string;
  "Foundation /Blue/blue-7": string;
  "Foundation /Blue/blue-8": string;
  "Foundation /Blue/blue-9": string;
  "Foundation /Blue/blue-10": string;
}

export interface ThemeTypography {
  "Bold/16": React.CSSProperties;
  "Medium/14": React.CSSProperties;
  "Medium/8": React.CSSProperties;
  "Regular/16": React.CSSProperties;
  "Body Strong": React.CSSProperties;
  "Body Base": React.CSSProperties;
  "ExtraBold/36": React.CSSProperties;
  "SemiBold/28": React.CSSProperties;
  "SemiBold/16": React.CSSProperties;
  "ExtraBold/18": React.CSSProperties;
  "Bold/18": React.CSSProperties;
  "ExtraBold/32": React.CSSProperties;
  "Medium/18": React.CSSProperties;
}

export const theme = {
  colors: {
    "White": "#FFFFFF",
    "M3/sys/light/on-surface": "#1D1B20",
    "M3/sys/light/error": "#B3261E",
    "TextIcon/OnNeutral": "#FFFFFF",
    "Foundation /Blue/blue-3": "#F5F8FF",
    "TextIcon/MidEmp": "#6C6C6C",
    "Foundation /Black/black-4": "#F0F0F0",
    "TextIcon/LowEmp": "#9E9E9E",
    "Foundation /Black/black-7": "#8C8C8C",
    "Foundation /Blue/blue-1": "#FFFFFF",
    "M3/sys/light/on-tertiary": "#FFFFFF",
    "Surface/NeutralBTN": "#000000",
    "Foundation/gray/gray-4": "#F0F0F0",
    "Foundation/gray/gray-8": "#595959",
    "Foundation/gray/gray-6": "#BFBFBF",
    "Foundation /Blue/blue-12": "#1466FF",
    "Foundation /Black/black-1": "#FFFFFF",
    "Foundation/black/text": "#141414",
    "Foundation/black/bg": "#141414",
    "Foundation/white/text": "#FFFFFF",
    "Foundation/white/bg": "#FFFFFF",
    "Foundation/gray/gray-5": "#D9D9D9",
    "Foundation/gray/gray-7": "#8C8C8C",
    "Foundation/gray/gray-2": "#FCFCFC",
    "Foundation /Blue/blue-2": "#CBCEFF",
    "Foundation /Blue/blue-4": "#787DFF",
    "Foundation /Blue/blue-5": "#4F56FF",
    "Foundation /Blue/blue-6": "#2831FF",
    "Foundation /Blue/blue-7": "#222AD9",
    "Foundation /Blue/blue-8": "#1C23B5",
    "Foundation /Blue/blue-9": "#171C91",
    "Foundation /Blue/blue-10": "#121673",
  },
  typography: {
    "Bold/16": {fontFamily:'Pretendard',fontWeight:700,fontSize:'16px',lineHeight:'23px',letterSpacing:'-0.4px'},
    "Medium/14": {fontFamily:'Pretendard',fontWeight:500,fontSize:'14px',lineHeight:'21px'},
    "Medium/8": {fontFamily:'Pretendard',fontWeight:500,fontSize:'8px',lineHeight:'10px'},
    "Regular/16": {fontFamily:'Pretendard',fontWeight:400,fontSize:'16px',lineHeight:'23px',letterSpacing:'-0.4px'},
    "Body Strong": {fontFamily:'Inter',fontWeight:600,fontSize:'16px',lineHeight:'22px'},
    "Body Base": {fontFamily:'Inter',fontWeight:400,fontSize:'16px',lineHeight:'22px'},
    "ExtraBold/36": {fontFamily:'Pretendard',fontWeight:800,fontSize:'36px',lineHeight:'43px'},
    "SemiBold/28": {fontFamily:'Pretendard',fontWeight:600,fontSize:'28px',lineHeight:'41px',letterSpacing:'-0.7000000000000001px'},
    "SemiBold/16": {fontFamily:'Pretendard',fontWeight:600,fontSize:'16px',lineHeight:'23px',letterSpacing:'-0.4px'},
    "ExtraBold/18": {fontFamily:'Pretendard',fontWeight:800,fontSize:'18px',lineHeight:'26px',letterSpacing:'-0.45px'},
    "Bold/18": {fontFamily:'Pretendard',fontWeight:700,fontSize:'18px',lineHeight:'26px',letterSpacing:'-0.45px'},
    "ExtraBold/32": {fontFamily:'Pretendard',fontWeight:800,fontSize:'32px',lineHeight:'46px'},
    "Medium/18": {fontFamily:'Pretendard',fontWeight:500,fontSize:'18px',lineHeight:'27px'},
  }
} as const;

export type Theme = typeof theme;
